using System;
using System.Collections.Generic;
using System.Linq;
using System.Speech.Synthesis;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Test2
{
    internal class Responses
    {
        SpeechSynthesizer talk = new SpeechSynthesizer();
        public string GetResponse(string question)//creting this method to create generated responses the user may ask
        {
            question = question.ToLower();//this will accept lower case input only 
           //the if and else if statements checks to see if the users input contains the word in the " "
           //The voice synthesis will read the responses to the user

            if (question.Contains("purpose"))
            {
                string response="My purpose is to help you stay safe online";
                talk.Speak(response);
                TypeEffects(response);
                return " ";
            }
            else if (question.Contains("cyber attack"))
            {
                string response="Phising";
                talk.Speak(response);
                TypeEffects(response);
                return " ";
            }
            else if (question.Contains("phising"))
            {
                string response=@"
Phising is a type of cyber attack where criminals impersonate organizations or individuals via 
email, text or phone to stealsensitive information like passwords";
                talk.Speak(response);
                TypeEffects(response);
                return " ";
            }
            else if (question.Contains("password"))
            {
                string response=@"
Always ensure your password is at least 16 characters long 
It should contain upper or lowercase letters It should contain numbers
It should contain a symbol 
AVOID USING 1 2 3 4 OR YOUR NAME
Example of a safe password: K%9vP2#zL0mN8qW!
But remember to keep the password saved so you do not forget";
                talk.Speak(response);
                TypeEffects(response);
                return " ";
            }
            else if (question.Contains("safe online browsing"))
            {
                string response=@"
Keep Browser Updated
Check for HTTPS
Avoid Public WI-FI
Use Ad Blockers
Use a password manager
Enable 2-step verification
Ignore pop up warnings";
                talk.Speak(response);
                TypeEffects(response);   
                return " ";
            }
            else if (question.Contains("hacking"))
            {
                string response=@"
Hacking is the unauthorized access to or
manipulation of, digital devices,networks
or data by exploiting security vulnerabilities.
";
                talk.Speak(response);
                TypeEffects(response);
                return " ";
            }
            else if (question.Contains("avoid hackers"))
            {
                string response=@"
Password management
Software Updates
Phising vigilance 
Firewalls & Anti-vurus
Device Security
";
                talk.Speak(response);
                TypeEffects(response);
                return " ";
            }
            else
            {
                //if the user did not input the right question this will display and the voice will say it aloud
                talk.Speak("I did not get that question please rephrase");
                TypeEffects("I Did not understand that could you rephrase");
                return " ";
            }
        }
        public  void TypeEffects(string text)
        {//this method adds a typing effect to the responses generated by the program
            Console.ForegroundColor = ConsoleColor.DarkBlue;
            foreach (char c in text)
            {
                Console.Write(c);
                Thread.Sleep(20);

            }
            Console.ResetColor();
            Console.WriteLine();
        }

    }
}

